---
- name: Install NodeJS playbook
  hosts: web
  # Run this playbook as superuser in target node
  become: true
  tasks:
   - name: Add NodeSource Node.js 20.x repo
     ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash - &&\sudo apt-get install -y nodejs

   - name: Install Node.js
     ansible.builtin.apt:
       name: nodejs
       state: present

   - name: Verify Node.js installation
     command: node -v
     register: node_version

   - name: Display Node.js version
     debug:
       msg: "Node.js version: {{ node_version.stdout }}"